### PR TITLE
compute shader supported

### PR DESCRIPTION
**Pull request by raptoravis**
compute shader supported

### CODE REVIEW

**Comment by septag** [comment]
Nice. Thank you.
It seems that the backends for metal/OpenGL is not ready yet. 
I will test the d3d version and get back to you

**Comment by raptoravis** [comment]
oh yes, but I can't manage to run the opengl version on windows(sorry that I can only have a PC), neither does metal.

btw, you might need to tweak sg_bind_flag as it was added for the compute shader stage.

**Comment by septag** [comment]
I'm trying to merge your code and also do some minor tweaks and clean it up.
the main problem is that sokol_gfx.h is reformatted and the diff is completely messed up (I should have probably turned clang-format off for these files).  could you undo formatting the file and just integrate the changes you have made ?

**Comment by septag** [comment]
never mind, I'll try to clean it up myself. they are some complications that I need to address them

**Comment by septag** [comment]
#7

**Pull request closed without merging**
