### PR TITLE
abspath needs to be normalized before attempting to find substring in…

### LINKED ISSUE #11: Hot reloading of shader doesn't seem to work on macOS
I've tried to recompile a shader on macOS while rizz is running a game plugin, and this causes an assert to fail in dmon.h. Here are the steps to reproduce

1) Clone repo
2) Build using Cmake
3) Run `./rizz  --run lib08-draw3d.dylib ` from the `bin` directory
4) Change the assignment statement in the fragment shader `draw3d.frag` for `frag_color` to something like - `frag_color = vec4(1.0, 0.0, 0.0, 1.0);`
5) Re-compile the sgs file using the following command - ```./tools/darwin/glslcc --vert=examples/08-draw3d/draw3d.vert --frag=examples/08-draw3d/draw3d.frag --lang=msl --reflect --sgs --output=examples/assets/shader
s/msl/draw3d.sgs```

This will cause the following assertion to fail - 

`Assertion failed: (strstr(abs_filepath, watch->rootdir) == abs_filepath), function dmon__fsevent_callback, file /Users/zacharycarter/dev/rizz/include/dmon/dmon.h, line 1347.`

### PR DESCRIPTION
**Pull request by zacharycarter**
… path being watched. There's also a memory leak in dmon.h on OSX.

Fixes https://github.com/septag/rizz/issues/11 & https://github.com/septag/rizz/issues/13

### CODE REVIEW

**Comment by zacharycarter** [comment]
@septag  - I'm not sure what the contribution guidelines are for this project, or if you are looking for others to contribute fixes. I found two issues with the directory monitoring code on OSX, which this PR addresses. I'm guessing you're quite busy, but whenever you have time to review these changes, please let me know if you'd like me to redo the PR or if you have any suggestions for changes.

Otherwise I'll just close this and keep the changes in my fork.

Thanks!

**Comment by septag** [comment]
Hi @zacharycarter ,
I'm very sorry dude, yeah, I was quite busy these past weeks, I couldn't check your changes. Luckily, I have some time now, I will check this tomorrow and get back to you.

Thanks

**Comment by zacharycarter** [comment]
> Hi @zacharycarter ,
> I'm very sorry dude, yeah, I was quite busy these past weeks, I couldn't check your changes. Luckily, I have some time now, I will check this tomorrow and get back to you.
> 
> Thanks

Thanks @septag! I figured you might be, especially with the Farcry announcement. No huge rush - just wanted to ensure you were interested in PRs.

**Comment by septag** [comment]
looks good to me, thank you very much!

> I figured you might be, especially with the Farcry announcement. No huge rush - just wanted to ensure you were interested in PRs.

haha, yeah, but I'm not working on that project. :) The main story is that MacOS is not my main dev platform, I have this shitty old iMac mini for dev, after the OS update, many things got messed up on it, so I'm just not that hyped to work on it, especially if I have not much time.

**Comment by RUSshy** [comment]
@zacharycarter shouldn't this PR be made in https://github.com/septag/dmon ?

**Comment by zacharycarter** [comment]
@RUSshy it's already been merged. I'll leave it to septag to apply the change to the dmon repo if they want to.

**Pull request merged**
