### PR TITLE
compute-shader support: Raptoravis upscs #5 #6

### PR DESCRIPTION
**Pull request by septag**
New changes to rapitoravis/upcs #6 :

- engine/example cleaning
- fixes to SGS (glslcc shaders) reflection data for compute-shaders
- removed the need to `begin_pass` before `dispatch`
- updated sokol_gfx
- resolved gcc/clang errors on platforms other than Windows
- fixed incorrect reformatting done to sokol_gfx

### CODE REVIEW

**Comment by septag** [comment]
@jonygli @raptoravis check out the new changes I made to your PR.
I've also added new reflection data to SGS shaders in order to not require manual loading of the shaders, the new glslcc compiler in this PR has that.

I moved `desc->bind_flag = SG_BIND_FLAG_COMPUTE_SHADER;` to `rizz__shader_setup_desc_cs`

Please check any possible mistakes with my changes because I'm not familiar with compute-shaders and just started learning it.

Do we have to support storage-buffers (SSBO) besides images ? if yes, could you extend the example to support those? I'm currently exporting their information in SGS files, I don't know how they are used.

There is also a new flag `compute_shaders` in `sg_features` which indicates wither the backend supports compute-shaders or not (which is currently only D3d11).

What are other stuff we should consider ?
After the primary features are fixed, can you start working on GL version? I think we can test GL backend on windows.

Looking forward to hearing your opinion 
Cheers,

**Comment by septag** [comment]
More changes and fixes:
- added more CS validity checks for `sg_validate_apply_binding` and `sg_make_shader`
- removed `sg_bind_flag`, instead, there is `shader_write` flag in sg_image_desc. the shaders will be automatically marked as compute_shader if you provide cs_source/byte_code

**Comment by raptoravis** [comment]
I looks perfect to me! esp. 
1. shader_write, it is definitely more easy than sg_bind_flag.
2. texelFetch, cs.comp really made me crazy as I had to use the hlsl. this really make me confortable.

thanks!

about storage-buffers (SSBO) , I am not sure either :(, I am still learning the modern advanced rendering tech. but for the purpose of adding compute shader, what I really wanted to test is to port the implementation of gpu driven rendering(https://github.com/bkaradzic/bgfx/tree/master/examples/37-gpudrivenrendering), in that example, I suppose SSBO is needed.

btw, it is ok for me to implement and test gl.

**Comment by septag** [comment]
cool. 
bgfx examples are nice to get started, also there is this example from bgfx:
https://github.com/bkaradzic/bgfx/tree/master/examples/24-nbody
that uses compute shaders, but I guess both of them uses indirect rendering and I think both of them introduce new concepts like indirect rendering, indirect buffers and whatnot.
But all in all, I think we should definitely add storage buffers (SSBO) because they are essential.

Also, I'd recommend that you check out DirectX samples:
https://github.com/walbourn/directx-sdk-samples

there are lots of compute-shader examples there that can be mapped more easily to our context which is d3d11 and they include from very primitive ones (BasicCompute11) to more advanced (OIT/NBodyGravity/...)

As for debugging tip, if you want to debug the calls and immediately trace them in sokol_gfx, use `immediate` mode API instead of `staged` (rename all staged to imm), after that you can add _cb calls to graphics.c for queuing in staged mode:

```c
        the_gfx->imm.apply_pipeline(g_quad.cspip);
        the_gfx->imm.apply_bindings(&g_quad.csbindings);
        the_gfx->imm.dispatch(512 / 16, 512 / 16, 1);
```

Don't hesitate to ask any questions, you actually pushed me to finish compute-shader feature at least on windows, so I'd be somewhat available to work on this.

**Comment by raptoravis** [comment]
thanks for the valuable info :)

**Comment by septag** [comment]
I'm letting you know that I'm currently working for _buffers_ support. so we wouldn't do duplicate work

**Comment by septag** [comment]
I guess the first experimental version of compute-shader support is ready.
I have implemented nbody gravity particles as an example, buffers are also working in this version

**Pull request merged**
